# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param:data
#' @param:K 初始聚类中心数目
#' @param:split=0.4 分裂参数
#' @param:theta_n 每一聚类中最少的样本数目 
#' @param:theta_S 一个聚类中样本距离分布的标准差
#' @param:theta_c 两聚类中心之间的最小距离，如小于此数，两个聚类进行合并
#' @param:L 每次迭代允许合并的最大聚类对数目
#' @param:I 允许的最多迭代次数
NULL

original_center <- function(data, k) {
    .Call(`_cluster_original_center`, data, k)
}

distEuclid <- function(v1, v2) {
    .Call(`_cluster_distEuclid`, v1, v2)
}

isodata <- function(data, k) {
    .Call(`_cluster_isodata`, data, k)
}

distEclud <- function(v1, v2) {
    .Call(`_cluster_distEclud`, v1, v2)
}

kmeans_c <- function(data, k) {
    .Call(`_cluster_kmeans_c`, data, k)
}

distManhattan <- function(v1, v2) {
    .Call(`_cluster_distManhattan`, v1, v2)
}

kmedians <- function(data, k) {
    .Call(`_cluster_kmedians`, data, k)
}

